In [2]:
import numpy as np

def qvec2rotmat(qvec):
    return np.array([
        [1 - 2 * qvec[2]**2 - 2 * qvec[3]**2,
         2 * qvec[1] * qvec[2] - 2 * qvec[0] * qvec[3],
         2 * qvec[3] * qvec[1] + 2 * qvec[0] * qvec[2]],
        [2 * qvec[1] * qvec[2] + 2 * qvec[0] * qvec[3],
         1 - 2 * qvec[1]**2 - 2 * qvec[3]**2,
         2 * qvec[2] * qvec[3] - 2 * qvec[0] * qvec[1]],
        [2 * qvec[3] * qvec[1] - 2 * qvec[0] * qvec[2],
         2 * qvec[2] * qvec[3] + 2 * qvec[0] * qvec[1],
         1 - 2 * qvec[1]**2 - 2 * qvec[2]**2]])


In [5]:
a = [0.9993528945148458,
     -0.02974519598698125, 0.007760852379294403,-0.018675778721175852]
T = [-0.012893501934982234, -0.024562324931854097, -0.42307952428242795]

R = qvec2rotmat(a)
print(R.T)

[[ 0.99918197 -0.03778908 -0.01440063]
 [ 0.03686569  0.99753288 -0.05974178]
 [ 0.01662269  0.05916202  0.99810998]]
